# Generated by Django 5.1.1 on 2024-12-23 18:28

import apps.common.services
import apps.contractors.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appendix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=200, verbose_name='Номер')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата')),
                ('note', models.CharField(blank=True, max_length=200, null=True, verbose_name='Примечание')),
            ],
            options={
                'verbose_name': 'Приложение к контракту',
                'verbose_name_plural': 'Приложениz к контрактам',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=200, verbose_name='Номер')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Контракт',
                'verbose_name_plural': 'Контракты',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Подрядчик',
                'verbose_name_plural': 'Подрядчики',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AppendixAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment_file', models.FileField(upload_to=apps.contractors.models.appendix_attachment_upload_path, validators=[apps.common.services.validate_scan_file], verbose_name='Файл')),
                ('file_size', models.CharField(blank=True, max_length=30, null=True, verbose_name='Размер файла')),
                ('appendix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='contractors.appendix', verbose_name='Приложение')),
            ],
            options={
                'verbose_name': 'Вложение приложения к контракту',
                'verbose_name_plural': 'Вложения приложений к контрактам',
            },
        ),
        migrations.AddField(
            model_name='appendix',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appendixes', to='contractors.contract', verbose_name='Контракт'),
        ),
        migrations.CreateModel(
            name='ContractAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment_file', models.FileField(upload_to=apps.contractors.models.contract_attachment_upload_path, validators=[apps.common.services.validate_scan_file], verbose_name='Файл')),
                ('file_size', models.CharField(blank=True, max_length=30, null=True, verbose_name='Размер файла')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='contractors.contract', verbose_name='Контракт')),
            ],
            options={
                'verbose_name': 'Вложение контракта',
                'verbose_name_plural': 'Вложения контрактов',
            },
        ),
        migrations.AddField(
            model_name='contract',
            name='contractor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='contractors.contractor', verbose_name='Контрагент'),
        ),
        migrations.AddConstraint(
            model_name='appendix',
            constraint=models.UniqueConstraint(fields=('contract', 'number'), name='unique_appendix_contract'),
        ),
    ]
