# Generated by Django 5.1.1 on 2024-12-23 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appendix',
            options={'ordering': ['date'], 'verbose_name': 'Приложение к контракту', 'verbose_name_plural': 'Приложения к контрактам'},
        ),
    ]
