# Generated by Django 5.1.1 on 2024-12-26 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0059_componentrepair_contractor'),
        ('contractors', '0005_alter_quotation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appendix',
            name='components',
            field=models.ManyToManyField(blank=True, related_name='appendixes', to='components.component', verbose_name='Компоненты'),
        ),
        migrations.AddField(
            model_name='contract',
            name='components',
            field=models.ManyToManyField(blank=True, related_name='contracts', to='components.component', verbose_name='Компоненты'),
        ),
    ]
