# Generated by Django 5.1.1 on 2024-12-26 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0007_contract_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='number',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Номер'),
        ),
    ]
