# Generated by Django 5.1.1 on 2025-01-09 13:12

import apps.common.services
import apps.contractors.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0009_remove_appendix_components_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30, verbose_name='Номер счета')),
                ('date', models.DateField(verbose_name='Дата')),
                ('note', models.CharField(blank=True, max_length=200, null=True, verbose_name='Примечание')),
                ('appendix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='contractors.appendix', verbose_name='Приложение к контракту')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='contractors.contract', verbose_name='Контракт')),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='contractors.contractor', verbose_name='Контрагент')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment_file', models.FileField(upload_to=apps.contractors.models.invoice_attachment_upload_path, validators=[apps.common.services.validate_scan_file], verbose_name='Файл')),
                ('file_size', models.CharField(blank=True, max_length=30, null=True, verbose_name='Размер файла')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='contractors.invoice', verbose_name='Счет')),
            ],
            options={
                'verbose_name': 'Вложение для счета',
                'verbose_name_plural': 'Вложения для счетов',
            },
        ),
    ]
