# Generated by Django 5.1.1 on 2025-01-09 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0010_invoice_invoiceattachment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'verbose_name': 'Счет', 'verbose_name_plural': 'Счета'},
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='appendix',
        ),
    ]
