# Generated by Django 5.1.1 on 2025-01-09 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0011_alter_invoice_options_remove_invoice_appendix'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appendixattachment',
            options={'verbose_name': 'Вложение для приложения к контракту', 'verbose_name_plural': 'Приложения к контрактам (вложения)'},
        ),
        migrations.AlterModelOptions(
            name='contractattachment',
            options={'verbose_name': 'Вложение контракта', 'verbose_name_plural': 'Контракты (вложения)'},
        ),
        migrations.AlterModelOptions(
            name='invoiceattachment',
            options={'verbose_name': 'Вложение для счета', 'verbose_name_plural': 'Счета (вложения)'},
        ),
        migrations.AlterModelOptions(
            name='quotationattachment',
            options={'verbose_name': 'Вложение для КП', 'verbose_name_plural': 'Коммерческие предложения (вложения)'},
        ),
    ]
