# Generated by Django 4.1.7 on 2024-08-26 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BucketCapacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.CharField(max_length=10, unique=True, verbose_name='Объем')),
            ],
            options={
                'verbose_name': 'Объем ковша',
                'verbose_name_plural': 'Объемы ковшей',
                'ordering': ['capacity'],
            },
        ),
        migrations.CreateModel(
            name='ToothAdapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Тип адаптера')),
            ],
            options={
                'verbose_name': 'Адаптер коронки',
                'verbose_name_plural': 'Адаптеры коронки',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Bucket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=3, null=True, verbose_name='Номер')),
                ('production_year', models.IntegerField(verbose_name='Год выпуска')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Примечание')),
                ('capacity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buckets', to='buckets.bucketcapacity', verbose_name='Объем')),
                ('tooth_adapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buckets', to='buckets.toothadapter', verbose_name='Адаптер')),
            ],
            options={
                'verbose_name': 'Ковк',
                'verbose_name_plural': 'Ковши',
                'ordering': ['number'],
            },
        ),
    ]
