# Generated by Django 4.1.7 on 2024-08-26 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BucketManufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Производитель')),
            ],
            options={
                'verbose_name': 'Производитель ковша',
                'verbose_name_plural': 'Производители ковшей',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='bucket',
            options={'ordering': ['number'], 'verbose_name': 'Ковш', 'verbose_name_plural': 'Ковши'},
        ),
        migrations.AddField(
            model_name='bucket',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buckets', to='buckets.bucketmanufacturer', verbose_name='Производитель'),
        ),
    ]
