# Generated by Django 4.1.7 on 2024-08-26 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0002_bucketmanufacturer_alter_bucket_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BucketSending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_side', models.CharField(max_length=30, verbose_name='Откуда')),
                ('to_side', models.CharField(max_length=30, verbose_name='Куда')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата')),
                ('bucket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sending', to='buckets.bucket', verbose_name='Ковш')),
            ],
            options={
                'verbose_name': 'Отправка ковша',
                'verbose_name_plural': 'Отправки ковшей',
                'ordering': ['date'],
            },
        ),
    ]
