# Generated by Django 4.1.7 on 2024-08-26 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0003_bucketsending'),
    ]

    operations = [
        migrations.CreateModel(
            name='BucketReceiving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_side', models.CharField(max_length=30, verbose_name='Откуда')),
                ('to_side', models.CharField(max_length=30, verbose_name='Куда')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата')),
                ('bucket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiving', to='buckets.bucket', verbose_name='Ковш')),
            ],
            options={
                'verbose_name': 'Приемка ковша',
                'verbose_name_plural': 'Приемки ковшей',
                'ordering': ['date'],
            },
        ),
    ]
