# Generated by Django 4.1.7 on 2024-08-26 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0005_alter_bucket_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='bucketreceiving',
            name='init_sending',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='buckets.bucketsending', verbose_name='Начальная отправка'),
        ),
    ]
