# Generated by Django 4.1.7 on 2024-08-27 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0007_bucketrelocation_remove_bucketsending_bucket_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bucketrelocation',
            name='relocate_status',
            field=models.CharField(blank=True, choices=[('sended', 'Отправлен'), ('resieved', 'Получен')], max_length=200, null=True, verbose_name='Статус перемещения'),
        ),
    ]
