# Generated by Django 4.1.7 on 2024-08-31 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0001_initial'),
        ('buckets', '0010_alter_bucket_number_alter_bucketrelocation_bucket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bucketrelocation',
            name='from_side',
        ),
        migrations.RemoveField(
            model_name='bucketrelocation',
            name='to_side',
        ),
        migrations.AddField(
            model_name='bucketrelocation',
            name='from_site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='buckets_relocations_from', to='sites.site', verbose_name='Откуда'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bucketrelocation',
            name='to_site',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='buckets_relocations_to', to='sites.site', verbose_name='Куда'),
            preserve_default=False,
        ),
    ]
