# Generated by Django 4.1.7 on 2024-08-31 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0011_remove_bucketrelocation_from_side_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bucketrelocation',
            options={'ordering': ['date'], 'verbose_name': 'Перемещение ковша', 'verbose_name_plural': 'Перемещения ковшей'},
        ),
        migrations.RemoveField(
            model_name='bucketrelocation',
            name='receive_date',
        ),
        migrations.RemoveField(
            model_name='bucketrelocation',
            name='send_date',
        ),
        migrations.AddField(
            model_name='bucketrelocation',
            name='date',
            field=models.DateField(default='2020-01-01', verbose_name='Дата перемещения'),
            preserve_default=False,
        ),
    ]
