# Generated by Django 4.1.7 on 2024-08-31 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0012_alter_bucketrelocation_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bucketrelocation',
            name='note',
        ),
        migrations.AddField(
            model_name='bucketrelocation',
            name='reason',
            field=models.TextField(default='1', verbose_name='Причина'),
            preserve_default=False,
        ),
    ]
