# Generated by Django 4.1.7 on 2024-08-31 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0014_rename_relocate_status_bucketrelocation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bucketrelocation',
            name='status',
            field=models.CharField(blank=True, choices=[('Отправлен', 'Отправлен'), ('Получен', 'Получен')], max_length=200, null=True, verbose_name='Статус перемещения'),
        ),
    ]
