# Generated by Django 4.1.7 on 2024-08-31 19:21

import apps.buckets.models.relocation
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0015_alter_bucketrelocation_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttachmentBucketRelocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment_file', models.FileField(upload_to=apps.buckets.models.relocation.attach_buck_reloc_upload_path, verbose_name='Файл вложения')),
                ('description', models.CharField(max_length=150, verbose_name='Описание')),
                ('bucket_relocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='buckets.bucketrelocation', verbose_name='Перемещение ковша')),
            ],
        ),
    ]
