# Generated by Django 4.1.7 on 2024-09-03 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0017_rename_attachmentbucketrelocation_bucketrelocationattachment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BucketControlPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Наименование')),
                ('note', models.CharField(max_length=200, verbose_name='Примечание')),
            ],
            options={
                'verbose_name': 'Точка контроля ковша',
                'verbose_name_plural': 'Точки контроля ковшей',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BucketInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата инспекции')),
                ('reason', models.CharField(max_length=200, verbose_name='Основание инспекции')),
                ('note', models.CharField(max_length=200, verbose_name='Примечание')),
                ('bucket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='buckets.bucket', verbose_name='Ковш')),
            ],
            options={
                'verbose_name': 'Инспекция ковша',
                'verbose_name_plural': 'Инспекции ковшей',
                'ordering': ['bucket'],
            },
        ),
        migrations.CreateModel(
            name='InspectionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=200, verbose_name='Примечание')),
                ('control_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections_results', to='buckets.bucketcontrolpoint', verbose_name='Точка контроля')),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections_results', to='buckets.bucketinspection', verbose_name='Инспецкция')),
            ],
            options={
                'verbose_name': 'Результат инспекции',
                'verbose_name_plural': 'Результаты инспекций',
                'ordering': ['inspection'],
            },
        ),
    ]
