# Generated by Django 4.1.7 on 2024-09-03 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0019_alter_bucketcontrolpoint_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bucketinspection',
            name='note',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Примечание'),
        ),
    ]
