# Generated by Django 5.1.1 on 2024-09-04 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0020_alter_bucketinspection_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectionresult',
            name='inspection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections_results', to='buckets.bucketinspection', verbose_name='Инспекция'),
        ),
        migrations.AlterField(
            model_name='inspectionresult',
            name='state',
            field=models.CharField(max_length=200, verbose_name='Состояние'),
        ),
    ]
