# Generated by Django 5.1.1 on 2024-09-06 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0023_historicalbucketrelocation_and_more'),
        ('equipments', '0009_alter_nameplate_attachment_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bucket',
            name='equipment_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buckets', to='equipments.equipmentmodel', verbose_name='Модель экскаватора'),
        ),
        migrations.AddField(
            model_name='bucket',
            name='nomencl_code',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Код номенклатуры'),
        ),
    ]
