# Generated by Django 5.1.1 on 2024-09-06 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0024_bucket_equipment_model_bucket_nomencl_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bucket',
            name='number',
            field=models.CharField(default='1', max_length=5, unique=True, verbose_name='Номер'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bucket',
            name='production_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Год выпуска'),
        ),
    ]
