# Generated by Django 5.1.1 on 2024-09-08 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0026_buckettechstate_historicalbuckettechstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='buckettechstate',
            name='description',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='historicalbuckettechstate',
            name='description',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='bucketrelocationattachment',
            name='description',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='historicalbucketrelocationattachment',
            name='description',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Описание'),
        ),
    ]
