# Generated by Django 5.1.1 on 2024-09-08 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0027_buckettechstate_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BucketTechStateOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Вариант техсостояния ковша',
                'verbose_name_plural': 'Варианты техсостояний ковшей',
                'ordering': ['name'],
            },
        ),
    ]
