# Generated by Django 5.1.1 on 2024-09-08 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0028_buckettechstateoption'),
    ]

    operations = [
        migrations.AddField(
            model_name='buckettechstate',
            name='techstate_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buckets_techstates', to='buckets.buckettechstateoption', verbose_name='Техсостояние'),
        ),
        migrations.AddField(
            model_name='historicalbuckettechstate',
            name='techstate_option',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='buckets.buckettechstateoption', verbose_name='Техсостояние'),
        ),
    ]
