# Generated by Django 5.1.1 on 2024-09-08 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0029_buckettechstate_techstate_option_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buckettechstate',
            name='techstate',
            field=models.CharField(blank=True, choices=[('Требует текущего ремонта', 'Требует текущего ремонта'), ('Требует капитального ремонта', 'Требует капитального ремонта'), ('Ремонта не требует', 'Ремонта не требует')], max_length=100, null=True, verbose_name='Техсостояние'),
        ),
        migrations.AlterField(
            model_name='historicalbuckettechstate',
            name='techstate',
            field=models.CharField(blank=True, choices=[('Требует текущего ремонта', 'Требует текущего ремонта'), ('Требует капитального ремонта', 'Требует капитального ремонта'), ('Ремонта не требует', 'Ремонта не требует')], max_length=100, null=True, verbose_name='Техсостояние'),
        ),
    ]
