# Generated by Django 5.1.1 on 2024-09-08 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0032_remove_buckettechstate_techstate_option_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buckettechstate',
            name='techstate',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='buckets_techstates', to='buckets.buckettechstateoption', verbose_name='Техсостояние'),
            preserve_default=False,
        ),
    ]
