# Generated by Django 5.1.1 on 2024-09-08 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0033_alter_buckettechstate_techstate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buckettechstate',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='historicalbuckettechstate',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
