# Generated by Django 5.1.1 on 2024-09-09 16:16

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0034_alter_buckettechstate_description_and_more'),
        ('equipments', '0009_alter_nameplate_attachment_file_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalBucket',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('number', models.CharField(db_index=True, max_length=5, verbose_name='Номер')),
                ('production_year', models.IntegerField(blank=True, null=True, verbose_name='Год выпуска')),
                ('nomencl_code', models.CharField(blank=True, max_length=15, null=True, verbose_name='Код номенклатуры')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Примечание')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('capacity', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='buckets.bucketcapacity', verbose_name='Объем')),
                ('equipment_model', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='equipments.equipmentmodel', verbose_name='Модель экскаватора')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('manufacturer', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='buckets.bucketmanufacturer', verbose_name='Производитель')),
                ('tooth_adapter', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='buckets.toothadapter', verbose_name='Адаптер')),
            ],
            options={
                'verbose_name': 'historical Ковш',
                'verbose_name_plural': 'historical Ковши',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.DeleteModel(
            name='HistoricalBucketCapacity',
        ),
    ]
