# Generated by Django 5.1.1 on 2024-09-10 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0036_bucketdecommission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bucketrelocation',
            name='status',
        ),
        migrations.RemoveField(
            model_name='historicalbucketrelocation',
            name='status',
        ),
        migrations.AddField(
            model_name='bucketrelocation',
            name='received',
            field=models.BooleanField(default=False, verbose_name='Получен'),
        ),
        migrations.AddField(
            model_name='historicalbucketrelocation',
            name='received',
            field=models.BooleanField(default=False, verbose_name='Получен'),
        ),
    ]
