# Generated by Django 5.1.1 on 2024-09-10 18:19

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0037_remove_bucketrelocation_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='bucketrelocation',
            name='received',
            field=models.BooleanField(default=False, verbose_name='Принят'),
        ),
        migrations.AlterField(
            model_name='historicalbucketrelocation',
            name='received',
            field=models.BooleanField(default=False, verbose_name='Принят'),
        ),
        migrations.CreateModel(
            name='BucketReconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата сверки')),
                ('bucket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliations', to='buckets.bucket', verbose_name='Ковш')),
            ],
            options={
                'verbose_name': 'Сверка данных ковша',
                'verbose_name_plural': 'Сверки данных ковша',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalBucketReconciliation',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата сверки')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('bucket', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='buckets.bucket', verbose_name='Ковш')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Сверка данных ковша',
                'verbose_name_plural': 'historical Сверки данных ковша',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
