# Generated by Django 5.1.1 on 2024-09-17 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0040_rename_reason_bucketrelocation_note_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BucketRelocationReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=50, verbose_name='Причина')),
            ],
            options={
                'verbose_name': 'Причина перемещения ковша',
                'verbose_name_plural': 'Причины перемещения ковшей',
            },
        ),
        migrations.AddField(
            model_name='bucketrelocation',
            name='reason',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buckets', to='buckets.bucketrelocationreason', verbose_name='Причина'),
        ),
        migrations.AddField(
            model_name='historicalbucketrelocation',
            name='reason',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='buckets.bucketrelocationreason', verbose_name='Причина'),
        ),
    ]
