# Generated by Django 5.1.1 on 2024-09-17 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0041_bucketrelocationreason_bucketrelocation_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bucketrelocation',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Примечание'),
        ),
        migrations.AlterField(
            model_name='bucketrelocation',
            name='reason',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='buckets', to='buckets.bucketrelocationreason', verbose_name='Причина'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicalbucketrelocation',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Примечание'),
        ),
    ]
