# Generated by Django 5.1.1 on 2024-09-19 12:24

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0042_alter_bucketrelocation_note_and_more'),
        ('equipments', '0009_alter_nameplate_attachment_file_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BucketInstallationReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=50, verbose_name='Причина')),
            ],
            options={
                'verbose_name': 'Причина установки/демонтажа ковша',
                'verbose_name_plural': 'Причины установки/демонтажа ковшей',
            },
        ),
        migrations.CreateModel(
            name='BucketInstallation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата установки')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Примечание')),
                ('bucket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buckets_installations', to='buckets.bucket', verbose_name='Ковш')),
                ('to_equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buckets_installations', to='equipments.equipment', verbose_name='Куда')),
                ('reason', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installation_buckets', to='buckets.bucketinstallationreason', verbose_name='Причина')),
            ],
            options={
                'verbose_name': 'Установка ковша',
                'verbose_name_plural': 'Установки ковшей',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='BucketDeinstallation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата демонтажа')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Примечание')),
                ('bucket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buckets_deinstallations', to='buckets.bucket', verbose_name='Ковш')),
                ('from_equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buckets_deinstallations', to='equipments.equipment', verbose_name='Откуда')),
                ('reason', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deinstallation_buckets', to='buckets.bucketinstallationreason', verbose_name='Причина')),
            ],
            options={
                'verbose_name': 'Демонтаж ковша',
                'verbose_name_plural': 'Демонтажи ковшей',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalBucketDeinstallation',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата демонтажа')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Примечание')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('bucket', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='buckets.bucket', verbose_name='Ковш')),
                ('from_equipment', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='equipments.equipment', verbose_name='Откуда')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reason', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='buckets.bucketinstallationreason', verbose_name='Причина')),
            ],
            options={
                'verbose_name': 'historical Демонтаж ковша',
                'verbose_name_plural': 'historical Демонтажи ковшей',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalBucketInstallation',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата установки')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Примечание')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('bucket', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='buckets.bucket', verbose_name='Ковш')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reason', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='buckets.bucketinstallationreason', verbose_name='Причина')),
                ('to_equipment', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='equipments.equipment', verbose_name='Куда')),
            ],
            options={
                'verbose_name': 'historical Установка ковша',
                'verbose_name_plural': 'historical Установки ковшей',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
