# Generated by Django 5.1.1 on 2024-09-20 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0043_bucketinstallationreason_bucketinstallation_and_more'),
        ('equipments', '0009_alter_nameplate_attachment_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bucketdeinstallation',
            name='bucket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bucket_deinstallations', to='buckets.bucket', verbose_name='Ковш'),
        ),
        migrations.AlterField(
            model_name='bucketdeinstallation',
            name='from_equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bucket_deinstallations', to='equipments.equipment', verbose_name='Откуда'),
        ),
        migrations.AlterField(
            model_name='bucketinstallation',
            name='bucket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bucket_installations', to='buckets.bucket', verbose_name='Ковш'),
        ),
        migrations.AlterField(
            model_name='bucketinstallation',
            name='reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='installation_buckets', to='buckets.bucketinstallationreason', verbose_name='Причина'),
        ),
        migrations.AlterField(
            model_name='bucketinstallation',
            name='to_equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bucket_installations', to='equipments.equipment', verbose_name='Куда'),
        ),
    ]
