# Generated by Django 5.1.1 on 2024-09-22 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0045_alter_bucket_options_alter_bucketcapacity_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bucketrepair',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='historicalbucketrepair',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата начала'),
        ),
    ]
