# Generated by Django 5.1.1 on 2024-09-22 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0046_alter_bucketrepair_start_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bucketrepair',
            options={'ordering': ['-pk'], 'verbose_name': 'Ремонт ковша', 'verbose_name_plural': 'Ремонты ковшей'},
        ),
        migrations.AddField(
            model_name='bucketrepair',
            name='worklist',
            field=models.TextField(default='-', verbose_name='Требуемые работы'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalbucketrepair',
            name='worklist',
            field=models.TextField(default='-', verbose_name='Требуемые работы'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bucketrepair',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Примечания'),
        ),
        migrations.AlterField(
            model_name='historicalbucketrepair',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Примечания'),
        ),
    ]
