# Generated by Django 5.1.1 on 2024-09-23 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0047_alter_bucketrepair_options_bucketrepair_worklist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bucketrepair',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2024-09-09 00:00:00', verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalbucketrepair',
            name='created_at',
            field=models.DateTimeField(blank=True, default='2024-09-09 00:00:00', editable=False, verbose_name='Дата создания'),
            preserve_default=False,
        ),
    ]
