# Generated by Django 5.1.1 on 2024-09-23 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0048_bucketrepair_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bucketrepair',
            old_name='created_at',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='historicalbucketrepair',
            old_name='created_at',
            new_name='date',
        ),
    ]
