# Generated by Django 5.1.1 on 2024-09-23 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0049_rename_created_at_bucketrepair_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bucketrepair',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='historicalbucketrepair',
            name='date',
            field=models.DateField(blank=True, editable=False, verbose_name='Дата создания'),
        ),
    ]
