# Generated by Django 5.1.1 on 2024-09-28 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0051_remove_bucketrelocation_received_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bucketinstallation',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='historicalbucketinstallation',
            name='reason',
        ),
    ]
