# Generated by Django 5.1.1 on 2024-09-30 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0052_remove_bucketinstallation_reason_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bucketinstallationreason',
            options={'verbose_name': 'Причина демонтажа ковша', 'verbose_name_plural': '(Справочник) Причины демонтажа ковшей'},
        ),
    ]
