# Generated by Django 5.1.1 on 2024-10-01 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0053_alter_bucketinstallationreason_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buckettechstateoption',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название'),
        ),
    ]
