# Generated by Django 5.1.1 on 2024-10-01 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0055_bucketinstallation_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bucketinstallation',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalbucketinstallation',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
