# Generated by Django 5.1.1 on 2024-10-01 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0057_delete_historicalbucketinstallation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bucketinstallation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2024-01-01'),
            preserve_default=False,
        ),
    ]
