# Generated by Django 5.1.1 on 2024-10-01 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0060_alter_bucketdeinstallation_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bucketdeinstallation',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
