# Generated by Django 5.1.1 on 2024-10-01 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0061_alter_bucketdeinstallation_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bucketdeinstallation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
