# Generated by Django 5.1.1 on 2024-10-02 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0067_remove_bucketreconciliation_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bucketreconciliation',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата сверки'),
        ),
    ]
