# Generated by Django 5.1.1 on 2024-10-03 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0069_alter_bucketrelocation_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BucketRelocationReason',
        ),
    ]
