# Generated by Django 5.1.1 on 2024-10-03 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0070_delete_bucketrelocationreason'),
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bucketrelocation',
            name='from_site',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_relocations_from_site', to='sites.site', verbose_name='Откуда'),
        ),
        migrations.AlterField(
            model_name='bucketrelocation',
            name='to_site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_relocations_to_site', to='sites.site', verbose_name='Куда'),
        ),
    ]
