# Generated by Django 5.1.1 on 2024-10-03 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0071_alter_bucketrelocation_from_site_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bucketrelocation',
            options={'ordering': ['-date'], 'verbose_name': 'Перемещение ковша', 'verbose_name_plural': 'Перемещения ковшей'},
        ),
    ]
