# Generated by Django 5.1.1 on 2024-10-03 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0072_alter_bucketrelocation_options'),
        ('common', '0002_deinstallationreason'),
        ('equipments', '0009_alter_nameplate_attachment_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bucketdeinstallation',
            name='reason',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deinstallation_buckets', to='common.deinstallationreason', verbose_name='Причина'),
        ),
        migrations.AlterField(
            model_name='bucketdeinstallation',
            name='from_equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_deinstallations', to='equipments.equipment', verbose_name='Откуда'),
        ),
        migrations.AlterField(
            model_name='bucketinstallation',
            name='to_equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_installations', to='equipments.equipment', verbose_name='Куда'),
        ),
        migrations.DeleteModel(
            name='BucketInstallationReason',
        ),
    ]
