# Generated by Django 5.1.1 on 2024-10-09 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0077_bucketcurrentdata'),
        ('equipments', '0009_alter_nameplate_attachment_file_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bucketcurrentdata',
            options={'ordering': ['bucket'], 'verbose_name': 'Текущие данные по ковшу', 'verbose_name_plural': 'Текущие данные по ковшам'},
        ),
        migrations.AlterField(
            model_name='bucketcurrentdata',
            name='equipment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bucket', to='equipments.equipment', verbose_name='Оборудование'),
        ),
    ]
