# Generated by Django 5.1.1 on 2024-10-10 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0082_bucketcurrentdata_is_being_repaired_and_more'),
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bucketcurrentdata',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buckets', to='sites.site', verbose_name='Мsестоположение'),
        ),
        migrations.AlterField(
            model_name='bucketcurrentdata',
            name='techstate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buckets', to='buckets.buckettechstateoption', verbose_name='Техсостояние'),
        ),
    ]
