# Generated by Django 5.1.1 on 2024-10-10 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0083_alter_bucketcurrentdata_location_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bucketcurrentdata',
            name='last_editor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Последний редактор'),
        ),
        migrations.AddField(
            model_name='bucketcurrentdata',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Дата редактирования'),
        ),
        migrations.DeleteModel(
            name='HistoricalBucket',
        ),
    ]
