# Generated by Django 5.1.1 on 2024-10-10 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0084_bucketcurrentdata_last_editor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bucketcurrentdata',
            old_name='last_editor',
            new_name='last_edit_by',
        ),
    ]
