# Generated by Django 5.1.1 on 2024-10-11 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0085_rename_last_editor_bucketcurrentdata_last_edit_by'),
        ('common', '0003_techstateoption'),
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bucketcurrentdata',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='sites.site', verbose_name='Местоположение'),
        ),
        migrations.AlterField(
            model_name='bucketcurrentdata',
            name='techstate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='common.techstateoption', verbose_name='Техсостояние'),
        ),
    ]
