# Generated by Django 5.1.1 on 2024-10-13 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0086_alter_bucketcurrentdata_location_and_more'),
        ('common', '0003_techstateoption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buckettechstate',
            name='techstate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buckets_techstates', to='common.techstateoption', verbose_name='Техсостояние'),
        ),
        migrations.DeleteModel(
            name='BucketTechStateOption',
        ),
    ]
