# Generated by Django 5.1.1 on 2024-10-15 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0089_alter_toothadapter_options_and_more'),
        ('common', '0003_techstateoption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bucketrelocation',
            name='reason',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.relocationreason', verbose_name='Причина'),
        ),
    ]
