# Generated by Django 5.1.1 on 2024-10-16 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0092_alter_bucketrelocation_from_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='bucket',
            name='requires_reconciliation',
            field=models.BooleanField(blank=True, null=True, verbose_name='Требует сверки'),
        ),
    ]
