# Generated by Django 5.1.1 on 2024-10-21 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0094_alter_bucket_requires_reconciliation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bucketcurrentdata',
            old_name='last_edit_by',
            new_name='updated_by',
        ),
    ]
