# Generated by Django 5.1.1 on 2024-11-24 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0097_alter_bucketrelocation_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bucketrelocation',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата перемещения'),
        ),
    ]
