# Generated by Django 5.1.1 on 2025-01-08 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0100_bucketrepair_author_historicalbucketrepair_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalBucketRepair',
        ),
    ]
