# Generated by Django 5.1.1 on 2025-01-25 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0102_rename_nomencl_code_bucket_nomenclature_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bucketrelocation',
            name='reason',
        ),
    ]
