# Generated by Django 5.1.1 on 2024-10-12 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_logger', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statuslog',
            options={'ordering': ('-create_datetime',), 'verbose_name': 'Logging', 'verbose_name_plural': 'Logging'},
        ),
        migrations.RenameField(
            model_name='statuslog',
            old_name='create_at',
            new_name='create_datetime',
        ),
    ]
