# Generated by Django 4.1.7 on 2023-05-09 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("equipments", "0001_initial"),
        ("equip_documents", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipmentdocument",
            name="equipment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="equipment_documents",
                to="equipments.equipment",
                verbose_name="Оборудование",
            ),
        ),
        migrations.AddField(
            model_name="equipmentdocument",
            name="equipment_group",
            field=models.ManyToManyField(
                related_name="equipment_documents",
                to="equip_documents.equipmentattachmentgroup",
                verbose_name="Группа оборудования",
            ),
        ),
    ]
