# Generated by Django 4.1.7 on 2023-05-10 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equip_documents', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachmenttype',
            name='slug',
            field=models.SlugField(default=1, unique=True, verbose_name='Слаг'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipmentattachmentgroup',
            name='slug',
            field=models.SlugField(default=1, unique=True, verbose_name='Слаг'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='equipmentdocument',
            name='attachment_file',
            field=models.FileField(upload_to='', verbose_name='Файл вложения'),
        ),
    ]
