# Generated by Django 4.1.7 on 2023-05-10 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equip_documents', '0003_attachmenttype_slug_equipmentattachmentgroup_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentdocument',
            name='equipment_group',
            field=models.ManyToManyField(blank=True, related_name='equipment_documents', to='equip_documents.equipmentattachmentgroup', verbose_name='Группа оборудования'),
        ),
    ]
