# Generated by Django 4.1.7 on 2023-05-10 17:14

import apps.equip_documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equip_documents', '0004_alter_equipmentdocument_equipment_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipmentattachmentgroup',
            name='slug',
        ),
        migrations.AlterField(
            model_name='equipmentdocument',
            name='attachment_file',
            field=models.FileField(upload_to=apps.equip_documents.models.get_upload_path, verbose_name='Файл вложения'),
        ),
    ]
