# Generated by Django 4.1.7 on 2023-05-11 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0002_remove_equipment_equipment_attachment_group'),
        ('equip_documents', '0005_remove_equipmentattachmentgroup_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentattachmentgroup',
            name='equipments',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='equipment_attachment_groups', to='equipments.equipment', verbose_name='Оборудование'),
            preserve_default=False,
        ),
    ]
