# Generated by Django 4.1.7 on 2023-05-11 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equip_documents', '0007_remove_equipmentattachmentgroup_equipments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentattachmentgroup',
            name='slug',
            field=models.SlugField(default=1, unique=True, verbose_name='Слаг'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='equipmentdocument',
            name='equipment_group',
        ),
        migrations.AddField(
            model_name='equipmentdocument',
            name='equipment_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipment_documents', to='equip_documents.equipmentattachmentgroup', verbose_name='Группа оборудования'),
        ),
    ]
