# Generated by Django 4.1.7 on 2023-05-21 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equip_documents', '0009_documenttype_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documenttype',
            options={'ordering': ['name'], 'verbose_name': 'Тип документа', 'verbose_name_plural': 'Типы документов'},
        ),
    ]
