# Generated by Django 5.1.1 on 2024-10-02 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Наименование компонента',
                'verbose_name_plural': '(Справочник) Наименования компонентов',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='component',
            name='component_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='components', to='components.componenttype', verbose_name='Тип'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='component',
            name='component_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='components', to='components.componentname', verbose_name='Наименование'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalcomponent',
            name='component_name',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='components.componentname', verbose_name='Наименование'),
        ),
    ]
