# Generated by Django 5.1.1 on 2024-10-02 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0002_componentname_alter_component_component_type_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ComponentType',
            new_name='ComponentKind',
        ),
        migrations.AlterModelOptions(
            name='componentkind',
            options={'ordering': ['name'], 'verbose_name': 'Вид компонента', 'verbose_name_plural': '(Справочник) Виды компонентов'},
        ),
        migrations.RemoveField(
            model_name='component',
            name='component_type',
        ),
        migrations.RemoveField(
            model_name='historicalcomponent',
            name='component_type',
        ),
        migrations.AddField(
            model_name='componentname',
            name='kind',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='component_names', to='components.componentkind', verbose_name='Вид'),
            preserve_default=False,
        ),
    ]
