# Generated by Django 5.1.1 on 2024-10-02 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0003_rename_componenttype_componentkind_and_more'),
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentRelocationReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=50, verbose_name='Причина')),
            ],
            options={
                'verbose_name': 'Причина перемещения компонента',
                'verbose_name_plural': '(Справочник) Причины перемещения компонентов',
            },
        ),
        migrations.CreateModel(
            name='ComponentRelocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата перемещения')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Примечание')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relocations', to='components.component', verbose_name='Компонент')),
                ('from_site', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='component_relocations_from', to='sites.site', verbose_name='Откуда')),
                ('to_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_relocations_to', to='sites.site', verbose_name='Куда')),
                ('reason', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_relocations', to='components.componentrelocationreason', verbose_name='Причина')),
            ],
            options={
                'verbose_name': 'Перемещение ковша',
                'verbose_name_plural': 'Перемещения ковшей',
                'ordering': ['-date'],
            },
        ),
    ]
