# Generated by Django 5.1.1 on 2024-10-03 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('components', '0004_componentrelocationreason_componentrelocation'),
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componentrelocation',
            name='reason',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.relocationreason', verbose_name='Причина'),
        ),
        migrations.AlterModelOptions(
            name='componentrelocation',
            options={'verbose_name': 'Перемещение компонента', 'verbose_name_plural': 'Перемещения компонентов'},
        ),
        migrations.AlterField(
            model_name='componentrelocation',
            name='from_site',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_relocations_from_site', to='sites.site', verbose_name='Откуда'),
        ),
        migrations.AlterField(
            model_name='componentrelocation',
            name='to_site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_relocations_to_site', to='sites.site', verbose_name='Куда'),
        ),
        migrations.DeleteModel(
            name='ComponentRelocationReason',
        ),
    ]
