# Generated by Django 5.1.1 on 2024-10-03 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0005_alter_componentrelocation_reason_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='componentrelocation',
            options={'ordering': ['-date'], 'verbose_name': 'Перемещение компонента', 'verbose_name_plural': 'Перемещения компонентов'},
        ),
    ]
