# Generated by Django 5.1.1 on 2024-10-03 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0006_alter_componentrelocation_options'),
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componentrelocation',
            name='from_site',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss_from_site', to='sites.site', verbose_name='Откуда'),
        ),
        migrations.AlterField(
            model_name='componentrelocation',
            name='to_site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss_to_site', to='sites.site', verbose_name='Куда'),
        ),
    ]
