# Generated by Django 5.1.1 on 2024-10-03 09:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_deinstallationreason'),
        ('components', '0007_alter_componentrelocation_from_site_and_more'),
        ('equipments', '0009_alter_nameplate_attachment_file_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentDeinstallation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата демонтажа')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Примечание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_deinstallations', to='components.component', verbose_name='Компонент')),
                ('from_equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='equipments.equipment', verbose_name='Откуда')),
                ('reason', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='common.deinstallationreason', verbose_name='Причина')),
            ],
            options={
                'verbose_name': 'Демонтаж компонента',
                'verbose_name_plural': 'Демонтажи компонентов',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ComponentInstallation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата установки')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Примечание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_installations', to='components.component', verbose_name='Компонент')),
                ('to_equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='equipments.equipment', verbose_name='Куда')),
            ],
            options={
                'verbose_name': 'Установка компонента',
                'verbose_name_plural': 'Установки компонентов',
                'ordering': ['-date'],
            },
        ),
    ]
