# Generated by Django 5.1.1 on 2024-10-03 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0008_componentdeinstallation_componentinstallation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='componentname',
            name='kind',
        ),
        migrations.RemoveField(
            model_name='component',
            name='component_name',
        ),
        migrations.RemoveField(
            model_name='historicalcomponent',
            name='component_name',
        ),
        migrations.RemoveField(
            model_name='historicalcomponent',
            name='history_user',
        ),
        migrations.AlterModelOptions(
            name='componentinstallation',
            options={'ordering': ['-date'], 'verbose_name': 'Монтаж компонента', 'verbose_name_plural': 'Монтажи компонентов'},
        ),
        migrations.DeleteModel(
            name='ComponentKind',
        ),
        migrations.DeleteModel(
            name='ComponentName',
        ),
        migrations.DeleteModel(
            name='HistoricalComponent',
        ),
    ]
