# Generated by Django 5.1.1 on 2024-10-03 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0009_remove_componentname_kind_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentKind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Вид компонента',
                'verbose_name_plural': '(Справочник) Виды компонентов',
                'ordering': ['name'],
            },
        ),
    ]
