# Generated by Django 5.1.1 on 2024-10-03 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0010_componentkind'),
        ('equipments', '0009_alter_nameplate_attachment_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True, verbose_name='Наименование')),
                ('equipment_models', models.ManyToManyField(blank=True, related_name='components_types', to='equipments.equipmentmodel', verbose_name='Модели оборудования')),
                ('kind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components_types', to='components.componentkind', verbose_name='Вид')),
            ],
            options={
                'verbose_name': 'Наименование компонента',
                'verbose_name_plural': '(Справочник) Наименования компонентов',
                'ordering': ['name'],
            },
        ),
    ]
