# Generated by Django 5.1.1 on 2024-10-03 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0011_componenttype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='componenttype',
            options={'ordering': ['name'], 'verbose_name': 'Тип компонента', 'verbose_name_plural': '(Справочник) Типы компонентов'},
        ),
        migrations.AddField(
            model_name='component',
            name='component_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='components', to='components.componenttype', verbose_name='Тип'),
            preserve_default=False,
        ),
    ]
