# Generated by Django 5.1.1 on 2024-10-03 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0015_alter_componenttypeequipmentmodel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentinstallation',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_installations', to='components.componentinstallationlocation', verbose_name='Место установки'),
        ),
        migrations.AlterField(
            model_name='componenttypeequipmentmodel',
            name='component_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_models', to='components.componenttype', verbose_name='Тип компонента'),
        ),
    ]
