# Generated by Django 5.1.1 on 2024-10-09 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0016_componentinstallation_location_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='componenttypeequipmentmodel',
            options={'verbose_name': 'Место установки компонента на модели оборудования', 'verbose_name_plural': 'Места установки компонентов на моделях оборудования'},
        ),
    ]
