# Generated by Django 5.1.1 on 2024-10-11 12:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_techstateoption'),
        ('components', '0019_alter_componentrelocation_author_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentTechState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата техсостояния')),
                ('is_operable', models.BooleanField(verbose_name='Подлежит эксплуатации')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='techstates', to='components.component', verbose_name='Компонент')),
                ('techstate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='common.techstateoption', verbose_name='Техсостояние')),
            ],
            options={
                'verbose_name': 'Техсостояние компонента',
                'verbose_name_plural': 'Техсостояния компонентов',
                'ordering': ['-date'],
            },
        ),
    ]
