# Generated by Django 5.1.1 on 2024-10-11 17:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_techstateoption'),
        ('components', '0020_componenttechstate'),
        ('equipments', '0009_alter_nameplate_attachment_file_and_more'),
        ('sites', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentCurrentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_being_repaired', models.BooleanField(blank=True, null=True, verbose_name='В ремонте')),
                ('is_operable', models.BooleanField(blank=True, null=True, verbose_name='Подлежит эксплуатации')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата редактирования')),
                ('component', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='current_data', to='components.component', verbose_name='Компонент')),
                ('equipment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='component', to='equipments.equipment', verbose_name='Оборудование')),
                ('last_edit_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Последний редактор')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='sites.site', verbose_name='Местоположение')),
                ('techstate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='common.techstateoption', verbose_name='Техсостояние')),
            ],
            options={
                'verbose_name': 'Текущие данные по компоненту',
                'verbose_name_plural': 'Текущие данные по компонентам',
                'ordering': ['component'],
            },
        ),
    ]
