# Generated by Django 5.1.1 on 2024-10-14 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0021_componentcurrentdata'),
        ('equipments', '0013_alter_equipment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componentcurrentdata',
            name='equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='component', to='equipments.equipment', verbose_name='Оборудование'),
        ),
    ]
