# Generated by Django 5.1.1 on 2024-10-15 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0024_componentcurrentdata_relocation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='number',
            field=models.CharField(max_length=50, unique=True, verbose_name='Номер'),
        ),
    ]
