# Generated by Django 5.1.1 on 2024-10-15 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0025_alter_component_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='serial_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Серийный номер'),
        ),
    ]
