# Generated by Django 5.1.1 on 2024-10-15 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0026_component_serial_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Подрядчик',
                'verbose_name_plural': 'Подрядчики',
                'ordering': ['-name'],
            },
        ),
    ]
