# Generated by Django 5.1.1 on 2024-10-15 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0027_contractor'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentrelocation',
            name='from_contractor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relocations_from', to='components.contractor', verbose_name='от подрядчика'),
        ),
        migrations.AddField(
            model_name='componentrelocation',
            name='to_contractor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relocations_to', to='components.contractor', verbose_name='к подрядчику'),
        ),
    ]
