# Generated by Django 5.1.1 on 2024-10-15 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0028_componentrelocation_from_contractor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='componentrelocation',
            name='to_contractor',
        ),
        migrations.RemoveField(
            model_name='componentrelocation',
            name='from_contractor',
        ),
        migrations.DeleteModel(
            name='Contractor',
        ),
    ]
