# Generated by Django 5.1.1 on 2024-10-16 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0032_alter_componentrelocation_from_site'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='componenttypeequipmentmodel',
            options={'ordering': ['component_type'], 'verbose_name': 'Место установки компонента на модели оборудования', 'verbose_name_plural': 'Места установки компонентов на моделях оборудования'},
        ),
    ]
