# Generated by Django 5.1.1 on 2024-10-16 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0033_alter_componenttypeequipmentmodel_options'),
        ('tasks', '0002_alter_task_options_task_author_task_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentTask',
            fields=[
                ('task_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tasks.task')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='components.component', verbose_name='Компонент')),
            ],
            bases=('tasks.task',),
        ),
    ]
