# Generated by Django 5.1.1 on 2024-10-16 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0034_componenttask'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='componenttask',
            options={'ordering': ['component'], 'verbose_name': 'Задача компонента', 'verbose_name_plural': 'Задачи компонентов'},
        ),
    ]
