# Generated by Django 5.1.1 on 2024-10-18 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0037_componentreconciliation'),
    ]

    operations = [
        migrations.AddField(
            model_name='componenttype',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Примечание'),
        ),
    ]
