# Generated by Django 5.1.1 on 2024-10-20 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0039_alter_component_options_alter_componenttype_name'),
        ('equipments', '0017_alter_equipmentrelocation_from_site'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='componenttypeequipmentmodel',
            constraint=models.UniqueConstraint(fields=('component_type', 'equipment_model', 'location'), name='unique_equipment_location'),
        ),
        migrations.AddConstraint(
            model_name='componenttypeequipmentmodel',
            constraint=models.UniqueConstraint(condition=models.Q(('location__isnull', True)), fields=('component_type', 'equipment_model'), name='unique_component_and_equipment_when_location_is_null'),
        ),
    ]
