# Generated by Django 5.1.1 on 2024-10-21 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0042_alter_componenttask_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='componentcurrentdata',
            old_name='last_edit_by',
            new_name='updated_by',
        ),
    ]
