# Generated by Django 5.1.1 on 2024-10-22 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0043_rename_last_edit_by_componentcurrentdata_updated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='is_serial_number_marked',
            field=models.BooleanField(default=False, verbose_name='Нанесен серийный номер'),
        ),
    ]
