# Generated by Django 5.1.1 on 2024-10-27 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0044_component_is_serial_number_marked'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentcurrentdata',
            name='installation_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата установки'),
        ),
    ]
