# Generated by Django 5.1.1 on 2024-11-22 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0046_componentstate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='nomenclature_code',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Код номенклатуры'),
        ),
    ]
