# Generated by Django 5.1.1 on 2024-11-24 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0049_alter_componentrelocation_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componentrelocation',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата перемещения'),
        ),
    ]
