# Generated by Django 5.1.1 on 2024-12-12 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0052_component_is_compliant_with_accounting'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentRepair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worklist', models.TextField(default='', verbose_name='Требуемые работы')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('completed_at', models.DateField(blank=True, null=True, verbose_name='Дата выполнения')),
                ('completed', models.BooleanField(default=False, verbose_name='Выполнено')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repairs', to='components.component', verbose_name='Компонент')),
            ],
            options={
                'verbose_name': 'Ремонт компонента',
                'verbose_name_plural': 'Ремонты компонентов',
                'ordering': ['-pk'],
            },
        ),
    ]
