# Generated by Django 5.1.1 on 2024-12-12 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0053_componentrepair'),
        ('sites', '0003_rename_is_contarctor_site_is_contractor'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentrepair',
            name='executor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='repairs', to='sites.site', verbose_name='Исполнитель'),
        ),
        migrations.AlterField(
            model_name='componentrepair',
            name='worklist',
            field=models.TextField(blank=True, default='', verbose_name='Требуемые работы'),
        ),
    ]
