# Generated by Django 5.1.1 on 2024-12-13 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0054_componentrepair_executor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentrepair',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Примечания'),
        ),
        migrations.AddField(
            model_name='componentrepair',
            name='plan_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Плановая дата окончания'),
        ),
    ]
