# Generated by Django 5.1.1 on 2024-12-16 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0055_componentrepair_note_componentrepair_plan_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentrepair',
            name='priority',
            field=models.CharField(choices=[('Срочно', 'Срочно'), ('Не срочно', 'Не срочно')], default='Не срочно', max_length=20, verbose_name='Приоритет'),
        ),
    ]
