# Generated by Django 5.1.1 on 2024-12-19 16:55

import apps.common.services
import apps.components.models.component
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0057_alter_component_nomenclature_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='number',
            field=models.CharField(max_length=50, unique=True, verbose_name='Порядковый номер'),
        ),
        migrations.CreateModel(
            name='ComponentAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment_file', models.FileField(upload_to=apps.components.models.component.component_attachment_upload_path, validators=[apps.common.services.validate_scan_file], verbose_name='Файл')),
                ('attachment_type', models.CharField(choices=[('Шильдик', 'Шильдик'), ('Фото компонента', 'Фото компонента')], max_length=30, verbose_name='Тип вложения')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file_size', models.CharField(blank=True, max_length=30, null=True, verbose_name='Размер файла')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authored_component_attachments', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='components.component', verbose_name='Компонент')),
            ],
            options={
                'verbose_name': 'Вложение компонента',
                'verbose_name_plural': 'Вложения компонентов',
            },
        ),
    ]
