# Generated by Django 5.1.1 on 2024-12-23 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0058_alter_component_number_componentattachment'),
        ('contractors', '0002_alter_appendix_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentrepair',
            name='contractor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='repairs', to='contractors.contractor', verbose_name='Подрядчик'),
        ),
    ]
