# Generated by Django 5.1.1 on 2024-12-29 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0060_componentrepair_appendix_componentrepair_contract'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='componentrepair',
            name='executor',
        ),
    ]
