# Generated by Django 5.1.1 on 2025-01-07 17:22

import apps.common.services
import apps.components.models.repair
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0061_remove_componentrepair_executor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentRepairAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment_file', models.FileField(upload_to=apps.components.models.repair.component_repair_attachment_upload_path, validators=[apps.common.services.validate_scan_file], verbose_name='Файл')),
                ('description', models.CharField(max_length=30, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file_size', models.CharField(blank=True, max_length=30, null=True, verbose_name='Размер файла')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authored_component_repair_attachments', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('repair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='components.componentrepair', verbose_name='Ремонт')),
            ],
            options={
                'verbose_name': 'Вложение ремонта компонента',
                'verbose_name_plural': 'Вложения ремонтов компонентов',
            },
        ),
    ]
