# Generated by Django 5.1.1 on 2025-01-09 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0063_remove_componentrepair_completed_and_more'),
        ('contractors', '0012_alter_appendixattachment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentrepair',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='repairs', to='contractors.invoice', verbose_name='Счет'),
        ),
    ]
