# Generated by Django 5.1.1 on 2025-01-12 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0064_componentrepair_invoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='is_compliant_with_accounting',
        ),
    ]
