# Generated by Django 5.1.1 on 2025-01-15 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0065_remove_component_is_compliant_with_accounting'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentattachment',
            name='description',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Описание'),
        ),
    ]
