# Generated by Django 5.1.1 on 2025-02-01 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0067_remove_componentrelocation_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componentattachment',
            name='attachment_type',
            field=models.CharField(choices=[('Шильдик', 'Шильдик'), ('Фото компонента', 'Фото компонента'), ('Другое', 'Другое')], max_length=30, verbose_name='Тип вложения'),
        ),
    ]
