# Generated by Django 5.1.5 on 2025-02-16 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0068_alter_componentattachment_attachment_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='requires_reconciliation',
        ),
        migrations.AddField(
            model_name='component',
            name='requires_action',
            field=models.BooleanField(default=False, verbose_name='Требуется действие'),
        ),
    ]
