# Generated by Django 5.1.1 on 2024-10-03 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeinstallationReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=50, verbose_name='Причина')),
            ],
            options={
                'verbose_name': 'Причина демонтажа',
                'verbose_name_plural': '(Справочник) Причины демонтажей',
            },
        ),
    ]
