# Generated by Django 5.1.1 on 2024-10-11 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_deinstallationreason'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechStateOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Вариант техсостояния',
                'verbose_name_plural': '(Справочник) Варианты техсостояний',
                'ordering': ['name'],
            },
        ),
    ]
