# Generated by Django 5.1.1 on 2025-01-25 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0103_remove_bucketrelocation_reason'),
        ('common', '0003_techstateoption'),
        ('components', '0067_remove_componentrelocation_reason'),
        ('equipments', '0037_remove_equipmentrelocation_reason'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RelocationReason',
        ),
    ]
