# Generated by Django 5.1.1 on 2024-10-27 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('sites', '0003_rename_is_contarctor_site_is_contractor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_titles', to='sites.site', verbose_name='Проект')),
                ('work_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_titles', to='sites.workcenter', verbose_name='Участок')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': '(Справочник) Должности',
            },
        ),
        migrations.CreateModel(
            name='UserJobTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_job_titles', to='sites.workcenter', verbose_name='Должность')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_job_titles', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Должность пользователя',
                'verbose_name_plural': 'Должности пользователей',
            },
        ),
    ]
