# Generated by Django 4.1.7 on 2023-10-31 11:58

import apps.events.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0009_alter_nameplate_attachment_file_and_more'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='equipments',
            field=models.ManyToManyField(blank=True, related_name='events', to='equipments.equipment', verbose_name='Оборудование'),
        ),
        migrations.CreateModel(
            name='EventFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment_file', models.FileField(upload_to=apps.events.models.get_eventfile_upload_path, verbose_name='Шильдик')),
                ('description', models.CharField(max_length=500, verbose_name='Описание')),
                ('file_size', models.CharField(blank=True, max_length=30, null=True, verbose_name='Размер файла')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Создано')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventfiles', to='events.event', verbose_name='Файлы событий')),
            ],
            options={
                'verbose_name': 'Файл события',
                'verbose_name_plural': 'Файлы событий',
            },
        ),
    ]
