# Generated by Django 4.1.7 on 2023-11-01 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0009_alter_nameplate_attachment_file_and_more'),
        ('events', '0003_alter_eventfile_attachment_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='equipments',
        ),
        migrations.AddField(
            model_name='event',
            name='equipment',
            field=models.ForeignKey(blank=True, default=7, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='equipments.equipment', verbose_name='Оборудование'),
            preserve_default=False,
        ),
    ]
