# Generated by Django 5.1.1 on 2025-01-18 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipments', '0036_equipment_decommissioned'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirefightingSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='firefighting', to='equipments.equipment', verbose_name='Оборудование')),
            ],
            options={
                'verbose_name': 'Система пожаротушения',
                'verbose_name_plural': 'Системы пожаротушения',
            },
        ),
    ]
