# Generated by Django 5.1.1 on 2025-01-18 14:24

import apps.firefighting.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firefighting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='firefightingsystem',
            name='requires_check',
            field=models.BooleanField(default=True, verbose_name='Требует проверки'),
        ),
        migrations.CreateModel(
            name='FirefightingCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата проверки')),
                ('attachment_file', models.FileField(upload_to=apps.firefighting.models.attach_firefighting_check_upload_path, verbose_name='Файл вложения')),
                ('state', models.CharField(choices=[('Исправна', 'Исправна'), ('Неисправна', 'Неисправна'), ('Неустановлена', 'Неустановлена')], max_length=20, verbose_name='Состояние')),
                ('note', models.CharField(blank=True, max_length=100, null=True, verbose_name='Примечание')),
                ('firefighting_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firefighting_checks', to='firefighting.firefightingsystem', verbose_name='Система пожаротушения')),
            ],
            options={
                'verbose_name': 'Проверка системы пожаротушения',
                'verbose_name_plural': 'Проверки систем пожаротушения',
            },
        ),
    ]
