# Generated by Django 5.1.1 on 2025-01-20 17:21

import apps.firefighting.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0036_equipment_decommissioned'),
        ('firefighting', '0002_firefightingsystem_requires_check_firefightingcheck'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='firefightingcheck',
            options={'ordering': ['-date'], 'verbose_name': 'Проверка системы пожаротушения', 'verbose_name_plural': 'Проверки систем пожаротушения'},
        ),
        migrations.AlterField(
            model_name='firefightingcheck',
            name='attachment_file',
            field=models.FileField(upload_to=apps.firefighting.models.attach_firefighting_check_upload_path, verbose_name='Файл акта проверки'),
        ),
        migrations.AlterField(
            model_name='firefightingcheck',
            name='date',
            field=models.DateField(verbose_name='Дата акта проверки'),
        ),
        migrations.AlterField(
            model_name='firefightingsystem',
            name='equipment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='firefighting_system', to='equipments.equipment', verbose_name='Оборудование'),
        ),
    ]
