# Generated by Django 5.1.5 on 2025-02-05 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firefighting', '0003_alter_firefightingcheck_options_and_more'),
        ('sites', '0004_site_warehouse_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='firefightingcheck',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sites.site', verbose_name='Место проведения проверки'),
            preserve_default=False,
        ),
    ]
