# Generated by Django 5.1.5 on 2025-02-16 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firefighting', '0004_firefightingcheck_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firefightingcheck',
            name='state',
            field=models.CharField(choices=[('Исправна', 'Исправна'), ('Неисправна', 'Неисправна'), ('Не установлена', 'Не установлена')], max_length=20, verbose_name='Состояние'),
        ),
    ]
