# Generated by Django 5.1.1 on 2025-01-31 08:33

import apps.documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment_file', models.FileField(upload_to=apps.documents.models.component_attachment_upload_path, verbose_name='Файл')),
                ('description', models.CharField(max_length=100, unique=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
            },
        ),
    ]
