# Generated by Django 4.1.7 on 2023-05-11 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='equipment_attachment_group',
        ),
    ]
