# Generated by Django 4.1.7 on 2023-05-21 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0002_remove_equipment_equipment_attachment_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Characteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('equipments', models.ManyToManyField(blank=True, related_name='equipment_characteristics', to='equipments.equipment', verbose_name='Оборудование')),
            ],
            options={
                'verbose_name': 'Характеристика',
                'verbose_name_plural': 'Характеристики',
                'ordering': ['name'],
            },
        ),
    ]
