# Generated by Django 4.1.7 on 2023-05-21 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0003_characteristic'),
    ]

    operations = [
        migrations.AddField(
            model_name='characteristic',
            name='value',
            field=models.CharField(default=1, max_length=100, verbose_name='Значение'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='characteristic',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='characteristic',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Примечание'),
        ),
    ]
