# Generated by Django 4.1.7 on 2023-05-21 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0004_characteristic_value_alter_characteristic_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='characteristic',
            name='value',
        ),
        migrations.CreateModel(
            name='EquipmentCharacteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100, verbose_name='Значение')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Примечание')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipments.equipment', verbose_name='Оборудование')),
                ('сharacteristic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipments.characteristic', verbose_name='Характеристика')),
            ],
        ),
    ]
