# Generated by Django 4.1.7 on 2023-05-21 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0005_remove_characteristic_value_equipmentcharacteristic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipmentcharacteristic',
            options={'verbose_name': 'Характеристика оборудования', 'verbose_name_plural': 'Характеристики оборудования'},
        ),
        migrations.AlterField(
            model_name='characteristic',
            name='equipments',
            field=models.ManyToManyField(blank=True, related_name='characteristics', to='equipments.equipment', verbose_name='Оборудование'),
        ),
        migrations.AlterField(
            model_name='equipmentcharacteristic',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_characteristics', to='equipments.equipment', verbose_name='Оборудование'),
        ),
        migrations.AlterField(
            model_name='equipmentcharacteristic',
            name='сharacteristic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipments_characteristic', to='equipments.characteristic', verbose_name='Характеристика'),
        ),
    ]
