# Generated by Django 4.1.7 on 2023-05-25 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0006_alter_equipmentcharacteristic_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacteristicGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Название')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Примечание')),
                ('equipments', models.ManyToManyField(blank=True, related_name='characteristic_groups', to='equipments.equipment', verbose_name='Оборудование')),
            ],
            options={
                'verbose_name': 'Группа оборудования по характеристикам',
                'verbose_name_plural': 'Группы оборудования по характеристикам',
            },
        ),
        migrations.RemoveField(
            model_name='characteristic',
            name='equipments',
        ),
        migrations.CreateModel(
            name='CharacteristicValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=80, verbose_name='Значение')),
                ('characteristic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characteristics', to='equipments.characteristic', verbose_name='Характеристика')),
                ('characteristic_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characteristic_groups', to='equipments.characteristicgroup', verbose_name='Группа оборудования по характеристикам')),
            ],
            options={
                'verbose_name': 'Значение характеристики',
                'verbose_name_plural': 'Значения характеристики',
            },
        ),
    ]
