# Generated by Django 4.1.7 on 2023-10-29 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0007_characteristicgroup_remove_characteristic_equipments_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nameplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment_file', models.FileField(upload_to='nameplates', verbose_name='Шильдик')),
                ('file_size', models.CharField(blank=True, max_length=30, null=True, verbose_name='Размер файла')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Создано')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_nameplates', to='equipments.equipment', verbose_name='Оборудование')),
            ],
            options={
                'verbose_name': 'Шильдик оборудования',
                'verbose_name_plural': 'Шильдики оборудования',
            },
        ),
        migrations.AlterModelOptions(
            name='characteristicvalue',
            options={'verbose_name': 'Величина характеристики', 'verbose_name_plural': 'Величины характеристик'},
        ),
        migrations.AlterField(
            model_name='characteristicvalue',
            name='characteristic_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characteristic_values', to='equipments.characteristicgroup', verbose_name='Группа оборудования по характеристикам'),
        ),
        migrations.DeleteModel(
            name='EquipmentCharacteristic',
        ),
    ]
