# Generated by Django 4.1.7 on 2023-10-31 11:58

import apps.equipments.models.nameplate
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0008_nameplate_alter_characteristicvalue_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nameplate',
            name='attachment_file',
            field=models.FileField(upload_to=apps.equipments.models.nameplate.equipment_upload_path, verbose_name='Шильдик'),
        ),
        migrations.AlterField(
            model_name='nameplate',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nameplates', to='equipments.equipment', verbose_name='Оборудование'),
        ),
    ]
