# Generated by Django 5.1.1 on 2024-10-12 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0010_equipmentcurrentdata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipmentcurrentdata',
            options={'ordering': ['equipment'], 'verbose_name': 'Текущие данные по оборудованию', 'verbose_name_plural': 'Текущие данные по оборудованию'},
        ),
    ]
