# Generated by Django 5.1.1 on 2024-10-13 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_techstateoption'),
        ('equipments', '0011_alter_equipmentcurrentdata_options'),
        ('sites', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentRelocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата перемещения')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Примечание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relocations', to='equipments.equipment', verbose_name='Ковш')),
                ('from_site', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss_from_site', to='sites.site', verbose_name='Откуда')),
                ('reason', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.relocationreason', verbose_name='Причина')),
                ('to_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss_to_site', to='sites.site', verbose_name='Куда')),
            ],
            options={
                'verbose_name': 'Перемещение оборудования',
                'verbose_name_plural': 'Перемещения оборудования',
                'ordering': ['-date'],
            },
        ),
    ]
