# Generated by Django 5.1.1 on 2024-10-13 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0012_equipmentrelocation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipment',
            options={'ordering': ['number'], 'verbose_name': 'Оборудование', 'verbose_name_plural': 'Оборудование'},
        ),
        migrations.RenameField(
            model_name='equipment',
            old_name='side_number',
            new_name='number',
        ),
        migrations.AlterField(
            model_name='equipmentrelocation',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relocations', to='equipments.equipment', verbose_name='Оборудование'),
        ),
    ]
