# Generated by Django 5.1.1 on 2024-10-21 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0017_alter_equipmentrelocation_from_site'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipmentcurrentdata',
            old_name='last_edit_by',
            new_name='updated_by',
        ),
    ]
