# Generated by Django 5.1.1 on 2024-11-22 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0018_rename_last_edit_by_equipmentcurrentdata_updated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentrelocation',
            name='order_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата приказа'),
        ),
        migrations.AddField(
            model_name='equipmentrelocation',
            name='order_number',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Номер приказа'),
        ),
    ]
