# Generated by Django 5.1.1 on 2024-11-23 17:06

import apps.equipments.models.relocation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0019_equipmentrelocation_order_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelocationOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, verbose_name='Номер приказа')),
                ('date', models.DateField(verbose_name='Дата приказа')),
                ('scan', models.FileField(blank=True, null=True, upload_to=apps.equipments.models.relocation.order_scan_upload_path, verbose_name='Скан приказа')),
            ],
            options={
                'verbose_name': 'Приказ на перемещение оборудования',
                'verbose_name_plural': 'Приказы на перемещения оборудования',
                'ordering': ['-date'],
                'constraints': [models.UniqueConstraint(fields=('number', 'date'), name='unique_number_date')],
            },
        ),
    ]
