# Generated by Django 5.1.1 on 2024-11-23 18:10

import apps.equipments.models.relocation
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0020_relocationorder'),
        ('sites', '0003_rename_is_contarctor_site_is_contractor'),
    ]

    operations = [
        migrations.AddField(
            model_name='relocationorder',
            name='from_site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='orders_from_site', to='sites.site', verbose_name='Откуда'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='relocationorder',
            name='to_site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='orders_to_site', to='sites.site', verbose_name='Куда'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='relocationorder',
            name='scan',
            field=models.FileField(blank=True, null=True, upload_to=apps.equipments.models.relocation.order_scan_upload_path, validators=[apps.equipments.models.relocation.validate_scan_file], verbose_name='Скан приказа'),
        ),
    ]
