# Generated by Django 5.1.1 on 2024-11-23 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0021_relocationorder_from_site_relocationorder_to_site_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='relocationorder',
            name='equipments',
            field=models.ManyToManyField(related_name='orders', to='equipments.equipment', verbose_name='Оборудование'),
        ),
    ]
