# Generated by Django 5.1.1 on 2024-11-24 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0023_relocationorder_author_relocationorder_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipmentrelocation',
            name='order_date',
        ),
        migrations.RemoveField(
            model_name='equipmentrelocation',
            name='order_number',
        ),
        migrations.AddField(
            model_name='equipmentrelocation',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipments_relocations', to='equipments.relocationorder', verbose_name='Приказ'),
        ),
    ]
