# Generated by Django 5.1.1 on 2024-11-24 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_techstateoption'),
        ('equipments', '0024_remove_equipmentrelocation_order_date_and_more'),
        ('sites', '0003_rename_is_contarctor_site_is_contractor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentrelocation',
            name='reason',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='common.relocationreason', verbose_name='Причина'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='equipmentrelocation',
            constraint=models.UniqueConstraint(fields=('equipment', 'order'), name='unique_equipment_order'),
        ),
    ]
