# Generated by Django 5.1.1 on 2024-11-24 18:50

import apps.equipments.models.relocation
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0027_alter_equipmentrelocation_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentrelocation',
            name='date',
            field=models.DateField(null=True, verbose_name='Дата перемещения'),
        ),
        migrations.CreateModel(
            name='RelocationAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attach_file', models.FileField(blank=True, null=True, upload_to=apps.equipments.models.relocation.relocation_attachment_upload_path, validators=[apps.equipments.models.relocation.validate_scan_file], verbose_name='Файл')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата редактирования')),
                ('file_size', models.CharField(blank=True, max_length=30, null=True, verbose_name='Размер файла')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authored_relocation_attachments', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('equipment_relocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relocation_attachments', to='equipments.equipmentrelocation', verbose_name='Перемещение')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relocation_attachments_last_edited', to=settings.AUTH_USER_MODEL, verbose_name='Последний редактор')),
            ],
            options={
                'verbose_name': 'Вложение для перемещения оборудования',
                'verbose_name_plural': 'Вложения для перемещений оборудования',
            },
        ),
    ]
