# Generated by Django 5.1.1 on 2024-11-24 18:55

import apps.equipments.models.relocation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0028_alter_equipmentrelocation_date_relocationattachment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='relocationattachment',
            options={'verbose_name': 'Вложение перемещения оборудования', 'verbose_name_plural': 'Вложения перемещений оборудования'},
        ),
        migrations.AlterField(
            model_name='relocationattachment',
            name='attach_file',
            field=models.FileField(default=1, upload_to=apps.equipments.models.relocation.relocation_attachment_upload_path, validators=[apps.equipments.models.relocation.validate_scan_file], verbose_name='Файл'),
            preserve_default=False,
        ),
    ]
