# Generated by Django 5.1.1 on 2024-11-24 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0029_alter_relocationattachment_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relocationattachment',
            old_name='attach_file',
            new_name='attachment_file',
        ),
    ]
