# Generated by Django 5.1.1 on 2024-11-29 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0030_rename_attach_file_relocationattachment_attachment_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relocationattachment',
            name='equipment_relocation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='equipments.equipmentrelocation', verbose_name='Перемещение'),
        ),
    ]
