# Generated by Django 5.1.1 on 2024-12-14 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0034_alter_relocationorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='inventory_number',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Инвентарный номер'),
        ),
    ]
