# Generated by Django 5.1.1 on 2024-12-25 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0035_equipment_inventory_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='decommissioned',
            field=models.BooleanField(default=False, verbose_name='Списан'),
        ),
    ]
