# Generated by Django 5.1.1 on 2025-01-25 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0037_remove_equipmentrelocation_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmetRunningTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('running_time', models.PositiveIntegerField(verbose_name='Общая наработка')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='running_times', to='equipments.equipment', verbose_name='Оборудование')),
            ],
            options={
                'verbose_name': 'Наработка оборудования',
                'verbose_name_plural': 'Наработки оборудования',
                'ordering': ['date'],
                'constraints': [models.UniqueConstraint(fields=('equipment', 'date'), name='unique_equipment_date')],
            },
        ),
    ]
