# Generated by Django 4.1.7 on 2023-05-09 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EquipmentMaintenanceGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Название"
                    ),
                ),
            ],
            options={
                "verbose_name": "Группа оборудования ТО",
                "verbose_name_plural": "Группы оборудования ТО",
            },
        ),
        migrations.CreateModel(
            name="MaintenanceCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Название"
                    ),
                ),
                (
                    "running_time",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Наработка для проведения"
                    ),
                ),
            ],
            options={
                "verbose_name": "Вид обслуживания",
                "verbose_name_plural": "Виды обслуживаний",
                "ordering": ["running_time"],
            },
        ),
        migrations.CreateModel(
            name="ScheduledMaintenanceWorkSystem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Название"
                    ),
                ),
            ],
            options={
                "verbose_name": "Система оборудования",
                "verbose_name_plural": "Системы оборудования",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ScheduledMaintenanceWork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Название"
                    ),
                ),
                (
                    "equipment_system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maintenance_works",
                        to="maintenance.scheduledmaintenanceworksystem",
                        verbose_name="Система оборудования",
                    ),
                ),
            ],
            options={
                "verbose_name": "Регламентная работа",
                "verbose_name_plural": "Регламентные работы",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="MaintenanceCardItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "material_quantity",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Количество материала"
                    ),
                ),
                (
                    "equipment_maintenance_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maintenance_card_items",
                        to="maintenance.equipmentmaintenancegroup",
                        verbose_name="Группа оборудования ТО",
                    ),
                ),
                (
                    "maintenance_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maintenance_card_items",
                        to="maintenance.maintenancecategory",
                        verbose_name="Вид ТО",
                    ),
                ),
                (
                    "scheduled_maintenance_work",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maintenance_card_items",
                        to="maintenance.scheduledmaintenancework",
                        verbose_name="Регламентная работа ТО",
                    ),
                ),
            ],
            options={
                "verbose_name": "Пункт карт ТО",
                "verbose_name_plural": "Пункты карт ТО",
                "ordering": ["maintenance_category"],
                "unique_together": {
                    (
                        "equipment_maintenance_group",
                        "maintenance_category",
                        "scheduled_maintenance_work",
                    )
                },
            },
        ),
    ]
