# Generated by Django 5.1.1 on 2025-01-11 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Склад',
                'verbose_name_plural': '(Справочник) Склады',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Nomenclature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Название')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Код')),
                ('number', models.CharField(max_length=20, verbose_name='Порядковый номер')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nomenclatures', to='importer.warehouse', verbose_name='Склад')),
            ],
            options={
                'verbose_name': 'Номенклатура',
                'verbose_name_plural': '(Справочник) Номенклатуры',
                'ordering': ['name'],
            },
        ),
    ]
