# Generated by Django 5.1.1 on 2025-01-11 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomenclature',
            name='number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Порядковый номер'),
        ),
    ]
