# Generated by Django 5.1.1 on 2025-01-11 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0002_alter_nomenclature_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomenclature',
            name='name',
            field=models.CharField(max_length=120, unique=True, verbose_name='Название'),
        ),
    ]
