# Generated by Django 5.1.1 on 2025-01-12 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0004_alter_warehouse_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Группа складов',
                'verbose_name_plural': '(Справочник) Группы складов',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='nomenclature',
            options={'ordering': ['name'], 'verbose_name': 'Номенклатура', 'verbose_name_plural': '(Справочник) Номенклатура'},
        ),
        migrations.AddField(
            model_name='warehouse',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='склады', to='importer.warehousegroup', verbose_name='Группа'),
        ),
    ]
