# Generated by Django 5.1.1 on 2025-01-22 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0005_warehousegroup_alter_nomenclature_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='name',
            field=models.CharField(max_length=60, unique=True, verbose_name='Название'),
        ),
    ]
