# Generated by Django 5.1.1 on 2025-01-29 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0006_alter_warehouse_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nomenclature',
            name='number',
        ),
    ]
