# Generated by Django 5.1.5 on 2025-03-07 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0007_remove_nomenclature_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomenclature',
            name='warehouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nomenclatures', to='importer.warehouse', verbose_name='Склад'),
        ),
    ]
