# Generated by Django 5.1.1 on 2025-01-12 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0005_warehousegroup_alter_nomenclature_options_and_more'),
        ('sites', '0003_rename_is_contarctor_site_is_contractor'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='warehouse_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sites', to='importer.warehousegroup', verbose_name='Группа складов'),
        ),
    ]
