# Generated by Django 5.1.1 on 2024-10-16 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_author_alter_task_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completion_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выполнения'),
        ),
        migrations.AddField(
            model_name='task',
            name='plan_completion_date',
            field=models.DateField(blank=True, null=True, verbose_name='Плановая дата выполнения'),
        ),
    ]
