# Generated by Django 5.1.1 on 2024-10-21 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_alter_task_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='done',
            new_name='completed',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='completion_date',
            new_name='completed_at',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='plan_completion_date',
            new_name='planned_completion_date',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='last_edit_by',
            new_name='updated_by',
        ),
        migrations.AddField(
            model_name='task',
            name='verified',
            field=models.BooleanField(default=False, verbose_name='Проверено'),
        ),
    ]
