# Generated by Django 5.1.1 on 2024-10-22 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_rename_done_task_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='accepted_for_execution',
            field=models.BooleanField(default=False, verbose_name='Принята к исполнению'),
        ),
    ]
