# Generated by Django 5.1.1 on 2024-11-05 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0019_rename_realizer_task_executor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='realizer_job_title',
            new_name='executor_job_title',
        ),
    ]
