# Generated by Django 5.1.1 on 2024-11-05 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0020_rename_realizer_job_title_task_executor_job_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='needs_comment',
            field=models.BooleanField(default=False, verbose_name='Требуется комментарий'),
        ),
    ]
