# Generated by Django 5.1.1 on 2024-11-18 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0021_task_needs_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('generic', 'Обычная задача'), ('component', 'Задача компонента')], default='generic', max_length=20, verbose_name='Тип задачи'),
        ),
    ]
