# Generated by Django 5.1.1 on 2024-11-22 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0023_task_has_been_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='accepted_for_execution',
        ),
    ]
