# Generated by Django 5.1.1 on 2024-12-09 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0025_remove_task_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('Срочно', 'Срочно'), ('Несрочно', 'Несрочно')], default='Несрочно', max_length=20, verbose_name='Приоритет'),
        ),
    ]
