# Generated by Django 5.1.1 on 2025-01-30 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0027_remove_task_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='priority',
        ),
    ]
