# Generated by Django 5.1.1 on 2025-02-01 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0028_remove_task_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='executor_job_title',
        ),
    ]
